"""
PatientInsight model - Letta-powered long-term insights
"""

from sqlalchemy import Column, String, Text, DateTime, ForeignKey, JSON, Float, Integer, Boolean
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid

from app.database.base import Base


class PatientInsight(Base):
    """
    PatientInsight model - Letta-powered insights

    Generated by querying Letta for patterns and learnings
    Examples:
    - "Patient tends to forget evening medications"
    - "Patient reports better mood after morning walks"
    - "Patient responds well to gentle reminders"
    """
    __tablename__ = "patient_insights"

    # Primary Key
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)

    # Foreign Keys
    patient_id = Column(
        UUID(as_uuid=True),
        ForeignKey("patients.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # Insight Type
    insight_type = Column(String(50), nullable=False)
    # Options: "pattern", "preference", "health_trend", "behavior", "communication", "recommendation"

    # Category
    category = Column(String(50), nullable=False)
    # Options: "medication", "mood", "activity", "communication", "health", "general"

    # Insight Content
    title = Column(String(200), nullable=False)  # "Prefers evening conversations"
    description = Column(Text, nullable=False)  # Detailed explanation

    # Supporting Evidence
    confidence_score = Column(Float, nullable=True)  # How confident Letta is (0.0-1.0)
    evidence_count = Column(Integer, nullable=True)  # How many data points support this

    supporting_data = Column(JSON, default=list)
    # Example: [{"date": "2025-10-20", "event": "missed morning med", "conversation_id": "123"}]

    # Actionable?
    is_actionable = Column(Boolean, default=False, nullable=False)
    suggested_action = Column(Text, nullable=True)  # What can be done about it

    # Source
    generated_by = Column(String(20), default="letta", nullable=False)  # "letta" or "claude"
    letta_query_used = Column(Text, nullable=True)  # What query was sent to Letta

    # Status
    is_active = Column(Boolean, default=True, nullable=False)  # Still relevant?
    relevance_end_date = Column(DateTime, nullable=True)  # When this insight becomes outdated

    # Timestamps
    first_observed_at = Column(DateTime, nullable=True)  # When pattern first appeared
    generated_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    patient = relationship("Patient", back_populates="insights")

    def __repr__(self):
        return f"<PatientInsight {self.insight_type}: {self.title} for patient {self.patient_id}>"
