"""add_mobile_setup_fields_to_patient

Revision ID: 0fce1b03abdf
Revises: 9a5c40d1e6f3
Create Date: 2025-10-25 11:23:39.978661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fce1b03abdf'
down_revision: Union[str, None] = '9a5c40d1e6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('setup_token', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('setup_token_expires', sa.DateTime(), nullable=True))
    # Add device_setup_completed as nullable first, set default, then make non-nullable
    op.add_column('patients', sa.Column('device_setup_completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE patients SET device_setup_completed = FALSE WHERE device_setup_completed IS NULL')
    op.alter_column('patients', 'device_setup_completed', nullable=False, server_default='false')
    op.add_column('patients', sa.Column('device_platform', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'device_platform')
    op.drop_column('patients', 'device_setup_completed')
    op.drop_column('patients', 'setup_token_expires')
    op.drop_column('patients', 'setup_token')
    # ### end Alembic commands ###
