"""add_caregiver_notes_table

Revision ID: 9a5c40d1e6f3
Revises: 7ccebe398c0e
Create Date: 2025-10-25 02:46:47.178117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5c40d1e6f3'
down_revision: Union[str, None] = '7ccebe398c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregiver_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('caregiver_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caregiver_notes_caregiver_id'), 'caregiver_notes', ['caregiver_id'], unique=False)
    op.create_index(op.f('ix_caregiver_notes_created_at'), 'caregiver_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_caregiver_notes_id'), 'caregiver_notes', ['id'], unique=False)
    op.create_index(op.f('ix_caregiver_notes_patient_id'), 'caregiver_notes', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_caregiver_notes_patient_id'), table_name='caregiver_notes')
    op.drop_index(op.f('ix_caregiver_notes_id'), table_name='caregiver_notes')
    op.drop_index(op.f('ix_caregiver_notes_created_at'), table_name='caregiver_notes')
    op.drop_index(op.f('ix_caregiver_notes_caregiver_id'), table_name='caregiver_notes')
    op.drop_table('caregiver_notes')
    # ### end Alembic commands ###
