"""Initial migration - create all tables with corrected types

Revision ID: a72a74be09a9
Revises: 
Create Date: 2025-10-24 21:58:28.469235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a72a74be09a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - manually adjusted for type casting ###
    # Use raw SQL with USING clause for proper type conversion
    op.execute('ALTER TABLE activity_logs ALTER COLUMN latitude TYPE DOUBLE PRECISION USING latitude::double precision')
    op.execute('ALTER TABLE activity_logs ALTER COLUMN longitude TYPE DOUBLE PRECISION USING longitude::double precision')
    op.execute('ALTER TABLE patient_caregiver_relationships ALTER COLUMN is_primary TYPE BOOLEAN USING is_primary::boolean')
    op.execute('ALTER TABLE patient_insights ALTER COLUMN confidence_score TYPE DOUBLE PRECISION USING confidence_score::double precision')
    op.execute('ALTER TABLE patient_insights ALTER COLUMN evidence_count TYPE INTEGER USING evidence_count::integer')
    op.execute('ALTER TABLE patient_insights ALTER COLUMN is_actionable TYPE BOOLEAN USING is_actionable::boolean')
    op.execute('ALTER TABLE patient_insights ALTER COLUMN is_active TYPE BOOLEAN USING is_active::boolean')
    op.execute('ALTER TABLE system_logs ALTER COLUMN duration_ms TYPE INTEGER USING duration_ms::integer')
    op.execute('ALTER TABLE system_logs ALTER COLUMN response_time_ms TYPE INTEGER USING response_time_ms::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - manually adjusted for type casting ###
    # Revert type changes back to VARCHAR
    op.execute('ALTER TABLE system_logs ALTER COLUMN response_time_ms TYPE VARCHAR')
    op.execute('ALTER TABLE system_logs ALTER COLUMN duration_ms TYPE VARCHAR')
    op.execute('ALTER TABLE patient_insights ALTER COLUMN is_active TYPE VARCHAR')
    op.execute('ALTER TABLE patient_insights ALTER COLUMN is_actionable TYPE VARCHAR')
    op.execute('ALTER TABLE patient_insights ALTER COLUMN evidence_count TYPE VARCHAR')
    op.execute('ALTER TABLE patient_insights ALTER COLUMN confidence_score TYPE VARCHAR')
    op.execute('ALTER TABLE patient_caregiver_relationships ALTER COLUMN is_primary TYPE VARCHAR')
    op.execute('ALTER TABLE activity_logs ALTER COLUMN longitude TYPE VARCHAR')
    op.execute('ALTER TABLE activity_logs ALTER COLUMN latitude TYPE VARCHAR')
    # ### end Alembic commands ###
